// Uses a public CORS proxy to bypass browser restrictions
const CORS_PROXY = 'https://api.allorigins.win/raw?url=';

export const fetchBilibiliSubtitles = async (videoUrl: string, onProgress: (msg: string) => void): Promise<string> => {
  try {
    // 1. Extract BV ID
    const bvMatch = videoUrl.match(/(BV[a-zA-Z0-9]+)/);
    if (!bvMatch) {
      throw new Error("Invalid Bilibili URL. Please ensure it contains a BV ID (e.g., BV1xx...).");
    }
    const bvid = bvMatch[1];

    onProgress(`Locating video metadata for ${bvid}...`);

    // 2. Fetch Video Page to get CID and AID
    // We add a timestamp to prevent caching
    const pageUrl = `${CORS_PROXY}${encodeURIComponent(`https://www.bilibili.com/video/${bvid}`)}&timestamp=${Date.now()}`;
    const pageResponse = await fetch(pageUrl);
    if (!pageResponse.ok) throw new Error("Failed to fetch video page info.");
    const pageHtml = await pageResponse.text();

    // 3. Parse INITIAL_STATE for cid and aid
    // Pattern looking for window.__INITIAL_STATE__={...};
    const stateMatch = pageHtml.match(/window\.__INITIAL_STATE__\s*=\s*({.+?});/);
    if (!stateMatch) {
      throw new Error("Could not parse video metadata from page. Bilibili might have changed their layout.");
    }

    const initialState = JSON.parse(stateMatch[1]);
    const aid = initialState.videoData?.aid;
    const cid = initialState.videoData?.cid;

    if (!aid || !cid) {
      throw new Error("Video ID (AID/CID) not found in metadata.");
    }

    onProgress("Checking for available subtitles...");

    // 4. Fetch Player API to get subtitle list
    const playerApiUrl = `${CORS_PROXY}${encodeURIComponent(`https://api.bilibili.com/x/player/v2?cid=${cid}&aid=${aid}`)}`;
    const playerResponse = await fetch(playerApiUrl);
    const playerData = await playerResponse.json();

    const subtitles = playerData?.data?.subtitle?.subtitles;

    if (!subtitles || subtitles.length === 0) {
       // Fallback: Check if there is at least an AI subtitle generated by Bilibili
       throw new Error("No CC subtitles found for this video. Please use the 'Upload Media' tab to upload the video/audio file instead.");
    }

    onProgress(`Found ${subtitles.length} subtitle track(s). Downloading...`);

    // 5. Select the best subtitle (Prefer JSON format)
    // Bilibili usually returns format within the url or mime type. 
    // We just take the first one usually, or prefer zh-CN.
    const selectedSub = subtitles.find((s: any) => s.lan === 'zh-CN') || subtitles[0];
    let subUrl = selectedSub.subtitle_url;

    // Ensure protocol
    if (subUrl.startsWith('//')) {
        subUrl = 'https:' + subUrl;
    }

    // 6. Fetch the actual subtitle content
    const subContentUrl = `${CORS_PROXY}${encodeURIComponent(subUrl)}`;
    const subContentResponse = await fetch(subContentUrl);
    
    // We assume it's JSON content because that's standard for Bilibili web player now
    const subText = await subContentResponse.text();
    
    return subText;

  } catch (error: any) {
    console.error("Bilibili Fetch Error:", error);
    if (error.message.includes("Failed to fetch")) {
        throw new Error("Network error. The proxy might be blocked or the URL is unreachable.");
    }
    throw error;
  }
};